name: Arc Deploy

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: lambda-logs # Optional.
      uses: Ilshidur/action-slack@master
      with:
        args: 'Portfolio Build Starting...'
    - uses: actions/checkout@v1
    - uses: actions/aws/cli@master
    - name: aws creds
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure --profile ft set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure --profile ft set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install project and arc
      run: |
        npm install
    - name: clientkit
      run: |
        npx clientkit prod
    - name: arc deploy
      if: success() && github.ref != 'refs/heads/master'
      run: |
        npx arc deploy
    - name: arc deploy production
      if: success() && github.ref == 'refs/heads/master'
      run: |
        npx arc deploy production
    - name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: lambda-logs # Optional.
      uses: Ilshidur/action-slack@master
      with:
        args: 'Portfolio Deployed!'


